### ISSUE TITLE
Diff view

### ISSUE THREAD

**Issue by shakram02** [CC451-Computer-Networks-TA-team/GraderX-FE#28]
- Display student diff

**Comment by shakram02** [comment]
https://github.com/praneshr/react-diff-viewer/tree/v2.0

**Comment by Hagar-Usama** [comment]
https://gist.github.com/amroakmal/645b16c8f8076a1b6866e359c4751661

**Comment by Hagar-Usama** [comment]
![accord_diff_res](https://user-images.githubusercontent.com/34040335/90777441-b8018f00-e2fb-11ea-9018-eec9d074f222.gif)

**Comment by Hagar-Usama** [comment]
https://github.com/CC451-Computer-Networks-TA-team/GraderX-FE/pull/37
